name: notify-deploy
on: page_build
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: ntfy
        run: |
          if [ "${{ github.event.build.status }}" = "built" ]; then
            curl -d "✅" https://ntfy.sh/tdd-deployed
          else
            curl -d "❌" https://ntfy.sh/tdd-deployed
          fi
